### ISSUE TITLE
qmrlab/mcrgui:v99.3.1 image didn't build SoS correctly.

### ISSUE THREAD

**Issue by mathieuboudreau** [rrsg2020/demo#4]
Modified the dockerfile in a new branch so that it would clone this repo: https://github.com/rrsg2020/demo/blob/binder_fix/Dockerfile

Two issues came up.

1 - I don't know where qMRLab is copied (it's not in HOME/work/qMRLab like my previous dockerfile)
2 - When trying an SoS notebook (https://mybinder.org/v2/gh/rrsg2020/demo/binder_fix?filepath=demo.ipynb), the left pannel of Jupyter complains about failed to locate subkernels Octave and Python , which usually happens when SoS isn't installed correctly. Also note, for my purposes, the versions of SoS, all kernels, and Plotly, must be **exactly** the same versions as those indicated in my old dockerfile, otherwise stuff will break (like here, but it may be broken for other reasons).

**Comment by agahkarakuzu** [comment]
I reverted the demo to its previous state. 

1 - qMRLab docker images save qMRLab to the Octave's default path, you can use it right away. It is under  $HOME, if you need to access. 

2 - I noticed that, will fix it.

**Comment by agahkarakuzu** [comment]
This is the `pip freeze` from the new env, and SoS is still complaining about something: 
```
alembic==0.9.9
appdirs==1.4.3
asn1crypto==0.24.0
async-generator==1.10
attrs==18.1.0
Automat==0.0.0
backcall==0.1.0
bleach==2.1.4
certifi==2018.8.13
cffi==1.11.5
chardet==3.0.4
Click==7.0
conda==4.5.8
constantly==15.1.0
cryptography==2.2.1
cycler==0.10.0
dash==1.7.0
dash-core-components==1.6.0
dash-dangerously-set-inner-html==0.0.2
dash-html-components==1.0.2
dash-renderer==1.2.2
dash-table==4.5.1
decorator==4.3.0
entrypoints==0.2.3
fasteners==0.15
feather-format==0.4.0
Flask==1.1.1
Flask-Compress==1.4.0
future==0.18.2
html5lib==1.0.1
hyperlink==17.3.1
idna==2.7
incremental==17.5.0
ipykernel==4.8.2
ipyparallel==6.2.4
ipython==6.5.0
ipython-genutils==0.2.0
itsdangerous==1.1.0
jedi==0.12.1
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.3
jupyter-core==4.4.0
jupyterhub==0.9.2
jupyterlab==0.34.0
jupyterlab-launcher==0.13.1
kiwisolver==1.1.0
Mako==1.0.7
Markdown==3.1.1
MarkupSafe==1.0
matplotlib==3.1.2
metakernel==0.24.3
mistune==0.8.3
monotonic==1.5
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.4
notebook==5.6.0
numpy==1.18.1
octave-kernel==0.31.0
osfclient==0.0.3
pamela==0.3.0
pandas==0.25.3
pandocfilters==1.4.2
parso==0.3.1
pexpect==4.6.0
pickleshare==0.7.4
plotly==4.4.1
portalocker==1.5.2
prometheus-client==0.3.0
prompt-toolkit==1.0.15
psutil==5.6.7
ptyprocess==0.6.0
pyarrow==0.15.1
pyasn1==0.4.4
pyasn1-modules==0.2.1
pycosat==0.6.3
pycparser==2.18
pycurl==7.43.0.2
pydot==1.4.1
pydotplus==2.0.2
Pygments==2.2.0
pyOpenSSL==18.0.0
pyparsing==2.4.6
PySocks==1.6.8
python-dateutil==2.7.3
python-editor==1.0.3
python-oauth2==1.0.1
pytz==2019.3
PyYAML==5.3
pyzmq==17.1.2
requests==2.19.1
retrying==1.3.3
ruamel-yaml==0.15.44
sas7bdat==2.2.3
saspy==3.1.9
scipy==1.4.1
Send2Trash==1.5.0
service-identity==17.0.0
simplegeneric==0.8.1
six==1.11.0

sos==0.17.7
sos-bash==0.12.3
sos-javascript==0.9.12.2
sos-julia==0.9.12.1
sos-matlab==0.9.12.1
sos-notebook==0.17.2
sos-python==0.9.12.1
sos-r==0.19.2
sos-ruby==0.9.15.0
sos-sas==0.9.12.3

SQLAlchemy==1.2.11
tabulate==0.8.6
terminado==0.8.1
testpath==0.3.1
tornado==5.1
tqdm==4.41.1
traitlets==4.3.2
Twisted==18.7.0
urllib3==1.23
Wand==0.5.8
wcwidth==0.1.7
webencodings==0.5
Werkzeug==0.16.0
xxhash==1.4.3
zope.interface==4.5.0
```

**Comment by agahkarakuzu** [comment]
Built function works: 

![image](https://user-images.githubusercontent.com/9632322/74405586-75ff0a00-4dfb-11ea-8dfe-2d6922b9a8b6.png)

I am having some issues with unzipping the file downloaded from the URL in your notebook. I tried to fit this one without a mask and with unmatching TIs, that's probably why it is taking long.

Here is the preview from `FitTempResults`:

![image](https://user-images.githubusercontent.com/9632322/74407879-efe5c200-4e00-11ea-9182-eff95f648d8e.png)

**Comment by agahkarakuzu** [comment]
BTW, you need to save using `save -mat7-binary` from Octave so that Matlab can read.

**Comment by mathieuboudreau** [comment]
> This is the `pip freeze` from the new env, and SoS is still complaining about something:

Here is a comparison between my environment (left) and yours (right).

<img width="1124" alt="Capture d’écran 2020-02-13 à 09 28 42" src="https://user-images.githubusercontent.com/1421029/74437886-833fe700-4e43-11ea-9f1f-3da04e651c1d.png">
<img width="1124" alt="Capture d’écran 2020-02-13 à 09 28 58" src="https://user-images.githubusercontent.com/1421029/74437891-863ad780-4e43-11ea-8a5d-02200019b5b4.png">
<img width="1124" alt="Capture d’écran 2020-02-13 à 09 29 10" src="https://user-images.githubusercontent.com/1421029/74437901-88049b00-4e43-11ea-8628-ca4fbefbff13.png">
<img width="1124" alt="Capture d’écran 2020-02-13 à 09 29 25" src="https://user-images.githubusercontent.com/1421029/74437910-8b982200-4e43-11ea-98ab-dd5c94c8beba.png">
<img width="1124" alt="Capture d’écran 2020-02-13 à 09 29 39" src="https://user-images.githubusercontent.com/1421029/74437918-8e931280-4e43-11ea-93b6-bf6ce2ee0d7e.png">

So, the reason why SoS isn't working for you might be that you need version `0.9.12.2` of sos-r, instead of `0.19.2` which is what you used. You'll also need version `3.10.0` of plotly, not `4.4.1` which will not work with my current plotly code.

This highlights another issue that I raised to you once before. I've been more of a fan of having full Dockerfiles instead of simply pulling them (like you did here) with a mostly empty dockerfile, because having a mostly empty dockerfile makes it more challenging for me as a developper to debut this kind of thing. I know you likely have your pre-build dockerfile settings saved somewhere on github/Dockerhub, however the issue is that it's not well documented where it's located (I don't know where to find it right now, and don't want to spend 20 minutes searching for it). We'll have to document this somewhere moving forward.

**Comment by mathieuboudreau** [comment]
Also, there are some other random python packages that don't match (e.g. pandas), by a significant version step. Not sure why, this is another thing that's hard to debug without seeing the dockerfile setup.

**Comment by agahkarakuzu** [comment]
Thanks for pointing out the mismatched versions, I will add them to the short Dockerfile to level environments. 

>This highlights another issue that I raised to you once before. I've been more of a fan of having full Dockerfiles instead of simply pulling them (like you did here)

We can easily downgrade/upgrade packages to match your environment. Minimizing RUN steps and basing from an env that has most of what we need yield faster and more stable builds. Imagine trying to get compiled MATLAB in the environment otherwise. 

> I know you likely have your pre-build dockerfile settings saved somewhere on github/Dockerhub

It is under `Deploy` folder of qMRLab. I think finding it is easier than finding the Dockerfile built `jupyter/basenotebook:33748fhsdbc4` (at least for us).

**Comment by mathieuboudreau** [comment]
> Thanks for pointing out the mismatched versions, I will add them to the short Dockerfile to level environments.
> 
> > This highlights another issue that I raised to you once before. I've been more of a fan of having full Dockerfiles instead of simply pulling them (like you did here)
> 
> We can easily downgrade/upgrade packages to match your environment. Minimizing RUN steps and basing from an env that has most of what we need yield faster and more stable builds. Imagine trying to get compiled MATLAB in the environment otherwise.
> 
> > I know you likely have your pre-build dockerfile settings saved somewhere on github/Dockerhub
> 
> It is under `Deploy` folder of qMRLab. I think finding it is easier than finding the Dockerfile built `jupyter/basenotebook:33748fhsdbc4` (at least for us).

Again, it's easy for you because you're the one who developped all of this. I just checked (https://github.com/qMRLab/qMRLab/blob/master/Deploy/Docker/OCTJN/requirements.txt) and couldnt find the sos-r version that's being used that you mentionned having an issue above. Not saying it's impossible, but clarity is the issue here.
